<a href="https://colab.research.google.com/github/AmbaliAnjane/DataScientist-Analyst_projects/blob/main/chuern_prediction(ann).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import tensorflow as tf
import numpy as np
import pandas as pd


In [3]:
#data preprcessing and cleansing
dataset=pd.read_csv("/content/Churn_Modelling.csv")

In [4]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [5]:
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [6]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [7]:
from sklearn.preprocessing import LabelEncoder#performed label encoding over gender column
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [8]:
print(x[:,2])

[0 0 0 ... 0 1 0]


In [10]:
from sklearn.preprocessing import OneHotEncoder#one hot encoding over others
from sklearn.compose import ColumnTransformer
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [11]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [12]:
from sklearn.preprocessing import StandardScaler#feature scaling
sc=StandardScaler()
x=sc.fit_transform(x)

In [13]:
x

array([[ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
         0.97024255,  0.02188649],
       [-1.00280393, -0.57873591,  1.74273971, ..., -1.54776799,
         0.97024255,  0.21653375],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011,  0.2406869 ],
       ...,
       [ 0.99720391, -0.57873591, -0.57380915, ..., -1.54776799,
         0.97024255, -1.00864308],
       [-1.00280393,  1.72790383, -0.57380915, ...,  0.64609167,
        -1.03067011, -0.12523071],
       [ 0.99720391, -0.57873591, -0.57380915, ...,  0.64609167,
        -1.03067011, -1.07636976]])

In [15]:
#spliting the dataset
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=.20,random_state=0)


In [16]:
#building the ANN model,model initializaiton
ann=tf.keras.models.Sequential()

In [18]:
#adding input layers & first hidden layer
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [19]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [20]:
#adding output layer
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [22]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])


In [23]:
#ann.fit(X_train, y_train, batch_size = 32, epochs = 100)
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 2ms/step - loss: 0.6047 - accuracy: 0.7221
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4890 - accuracy: 0.8034
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4550 - accuracy: 0.8076
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4414 - accuracy: 0.8079
Epoch 5/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4324 - accuracy: 0.8112
Epoch 6/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4255 - accuracy: 0.8117
Epoch 7/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4200 - accuracy: 0.8135
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4150 - accuracy: 0.8146
Epoch 9/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4105 - accuracy: 0.8156
Epoch 10/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4068 - accura

In [24]:
#done with training model ,let's predict the test results
y_pred=ann.predict(x_test)

63/63 [==============================] - 0s 1ms/step


In [25]:
y_pred

array([[0.25711793],
       [0.24314743],
       [0.11216044],
       ...,
       [0.17933388],
       [0.22996941],
       [0.14263466]], dtype=float32)

In [29]:
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [30]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1510   85]
 [ 190  215]]


In [31]:
from sklearn.metrics import accuracy_score
acc=accuracy_score(y_pred,y_test)
print(acc)

0.8625
