<a href="https://colab.research.google.com/github/AmbaliAnjane/DataScientist-Analyst_projects/blob/main/earthquake_tweet_classifier.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [53]:
import numpy as np
import pandas as pd
import re

In [54]:
df=pd.read_csv("/content/train.csv")

In [55]:
df

id keyword location  \
0         1     NaN      NaN   
1         4     NaN      NaN   
2         5     NaN      NaN   
3         6     NaN      NaN   
4         7     NaN      NaN   
...     ...     ...      ...   
7608  10869     NaN      NaN   
7609  10870     NaN      NaN   
7610  10871     NaN      NaN   
7611  10872     NaN      NaN   
7612  10873     NaN      NaN   

                                                   text  target  
0     Our Deeds are the Reason of this #earthquake M...       1  
1                Forest fire near La Ronge Sask. Canada       1  
2     All residents asked to 'shelter in place' are ...       1  
3     13,000 people receive #wildfires evacuation or...       1  
4     Just got sent this photo from Ruby #Alaska as ...       1  
...                                                 ...     ...  
7608  Two giant cranes holding a bridge collapse int...       1  
7609  @aria_ahrary @TheTawniest The out of control w...       1  
7610  M1.94 [01:04 UTC]?5km S of Volcano Hawaii. htt...       1  
7611  Police investigating after an e-bike collided ...       1  
7612  The Latest: More Homes Razed by Northern Calif...       1  

[7613 rows x 5 columns]

In [56]:
dataset=df.dropna(axis=1)

In [57]:
df.isna().sum()

id             0
keyword       61
location    2533
text           0
target         0
dtype: int64

In [58]:
dataset.isna().sum()

id        0
text      0
target    0
dtype: int64

In [59]:
dataset.shape

(7613, 3)

In [65]:
x=dataset.iloc[:,1:2].values

In [66]:
x

array([['Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'],
       ['Forest fire near La Ronge Sask. Canada'],
       ["All residents asked to 'shelter in place' are being notified by officers. No other evacuation or shelter in place orders are expected"],
       ...,
       ['M1.94 [01:04 UTC]?5km S of Volcano Hawaii. http://t.co/zDtoyd8EbJ'],
       ['Police investigating after an e-bike collided with a car in Little Portugal. E-bike rider suffered serious non-life threatening injuries.'],
       ['The Latest: More Homes Razed by Northern California Wildfire - ABC News http://t.co/YmY4rSkQ3d']],
      dtype=object)

In [68]:
y=dataset.iloc[:,2].values
y

array([1, 1, 1, ..., 1, 1, 1])

In [69]:
import spacy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import nltk

In [70]:
stopwords=nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [71]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = [] 
for i in range(0,7613):
    text = re.sub('[^a-zA-Z]', ' ', dataset['text'][i])
    text = text.lower()
    text = text.split()
    ps = PorterStemmer()
    text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
    text = ' '.join(text)
    corpus.append(text)



In [137]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(corpus,y,test_size=.20,random_state=0)

In [138]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
cv_train=cv.fit_transform(X_train).toarray()
cv_test =cv.transform(X_test).toarray()


In [139]:
np.shape(y_train)

(5329,)

In [140]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(cv_train,y_train)


GaussianNB()

In [141]:
y_pred = classifier.predict(cv_test)

In [142]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_pred,y_test)
print(cm)


[[612 188]
 [726 758]]


In [143]:
from sklearn.metrics import accuracy_score
ac = accuracy_score(y_test, y_pred)
print(ac)
  

0.5998248686514887


In [144]:
bias = classifier.score(cv_train,y_train)
variance = classifier.score(cv_test,y_test)
print('bias :',bias ,'\n variance:',variance)


bias : 0.9452054794520548 
 variance: 0.5998248686514887


In [145]:
test_set=pd.read_csv("/content/test.csv")

In [95]:
test_set

id keyword location  \
0         0     NaN      NaN   
1         2     NaN      NaN   
2         3     NaN      NaN   
3         9     NaN      NaN   
4        11     NaN      NaN   
...     ...     ...      ...   
3258  10861     NaN      NaN   
3259  10865     NaN      NaN   
3260  10868     NaN      NaN   
3261  10874     NaN      NaN   
3262  10875     NaN      NaN   

                                                   text  
0                    Just happened a terrible car crash  
1     Heard about #earthquake is different cities, s...  
2     there is a forest fire at spot pond, geese are...  
3              Apocalypse lighting. #Spokane #wildfires  
4         Typhoon Soudelor kills 28 in China and Taiwan  
...                                                 ...  
3258  EARTHQUAKE SAFETY LOS ANGELES ‰ÛÒ SAFETY FASTE...  
3259  Storm in RI worse than last hurricane. My city...  
3260  Green Line derailment in Chicago http://t.co/U...  
3261  MEG issues Hazardous Weather Outlook (HWO) htt...  
3262  #CityofCalgary has activated its Municipal Eme...  

[3263 rows x 4 columns]

In [96]:
test_set1=test_set.dropna(axis=1)

In [97]:
test_set1.isna().sum()

id      0
text    0
dtype: int64

In [98]:
test_set1.shape

(3263, 2)

In [129]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus2 = [] 
for i in range(0,3263):
    text = re.sub('[^a-zA-Z]', ' ', test_set['text'][i])
    text = text.lower()
    text = text.split()
    ps = PorterStemmer()
    text = [ps.stem(word) for word in text if not word in set(stopwords.words('english'))]
    text = ' '.join(text)
    corpus2.append(text)



In [133]:
X_testset =cv.transform(corpus2).toarray()


In [134]:
y_pred_testset = classifier.predict(X_testset)

In [135]:
y_pred_testset

array([1, 1, 1, ..., 1, 1, 1])

In [136]:
len(y_pred_testset)

3263

In [168]:
from numpy.core.numeric import identity
# creating a list of index names
id1 = [i for i in range(3263)]
d = {'id': id1, 'target':y_pred_testset}
df = pd.DataFrame(data=d)
   



In [169]:
df

id  target
0        0       1
1        1       1
2        2       1
3        3       1
4        4       1
...    ...     ...
3258  3258       1
3259  3259       1
3260  3260       1
3261  3261       1
3262  3262       1

[3263 rows x 2 columns]